version: "3.7"
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONF_TYPE: ${CONF_TYPE:-default}
    environment:
      - PROXY_HOST=${PROXY_HOST}
    ports:
      - "80:80"
